### ISSUE TITLE
Executables are viruses?

### ISSUE THREAD

**Issue by rdeveen** [pablocastro/minimute#2]
Downloading the .exe from the release folder gives antivirus warning, trojan detected.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWoreflint.A!cl&threatid=2147723317

**Comment by pablocastro** [comment]
Thanks for reporting. I got the same message from windows defender even for the binary I built locally. I filed a windows defender report indicating it was a false positive, I'm not sure how much of an effect that'll have, but hopefully it'll help.

Ultimately, Windows really doesn't like unsigned binaries for obvious security concerns. I'll see if at least I sign future exes with a self-signed cert.
